name: Build and Release

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Ejecutar diariamente a las 2 AM

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Compile Python scripts
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile --hidden-import=json --hidden-import=subprocess scripts/control-server.py --name vm-service.exe
        Move-Item dist/vm-service.exe bin/
    
    - name: Download VirtualBox
      run: |
        $vboxUrl = "https://download.virtualbox.org/virtualbox/7.0.16/VirtualBox-7.0.16-162802-Win.exe"
        Invoke-WebRequest -Uri $vboxUrl -OutFile "bin/virtualbox.exe"
    
    - name: Create zip package
      run: |
        Compress-Archive -Path * -DestinationPath stealth-vm-manager.zip -Force
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: stealth-vm-manager.zip
        generate_release_notes: true
